version: "2"
services:
    odoo:
        image: odoo:10.0
        platform: linux/amd64
        container_name: odoo10
        depends_on:
            - postgresql
        tty: true
        stdin_open: true
        ports:
            - "9003:8069"
            - "9004:8072"
        volumes:
            - ./addons:/mnt/extra-addons
            - ./conf:/etc/odoo
        environment:
            - HOST=postgres
        restart: always
    postgresql:
        image: postgres:9.4
        container_name: postgres
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_PASSWORD=odoo
            - POSTGRES_USER=odoo
        ports:
            - "5502:5432"