version: "3.6"
services:
    odoo:
        image: odoo:17.0
        platform: linux/amd64
        container_name: odoo17
        depends_on:
            - postgresql
        tty: true
        stdin_open: true
        ports:
            - "9001:8069"
            - "9002:8072"
        volumes:
            - ./addons:/mnt/extra-addons
            - ./conf:/etc/odoo
        environment:
            - HOST=postgres
        restart: always
    postgresql:
        image: postgres:15.0
        container_name: postgres
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_PASSWORD=odoo
            - POSTGRES_USER=odoo
        ports:
            - "5501:5432"